# Generated by Django 5.1.7 on 2025-03-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Off Duty', 'Off Duty'), ('Sleeper Berth', 'Sleeper Berth'), ('Driving', 'Driving'), ('On Duty, Not Driving', 'On Duty')], default='Off Duty', max_length=100)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('duration', models.DurationField()),
                ('rest_stop', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
