# Generated by Django 5.1.7 on 2025-03-27 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log_book', '0001_initial'),
        ('trips', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='co_driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_driver_log_entries', to='users.driver'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_log_entries', to='users.driver'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='trips.trip'),
        ),
    ]
